//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creations.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expedient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expedient()
        {
            this.EvaluationCompleted = new HashSet<EvaluationCompleted>();
        }
    
        public int Id { get; set; }
        public int IdAlumno { get; set; }
        public int IdEvaluationCompleted { get; set; }
        public int Score { get; set; }
        public int Attemp { get; set; }
        public System.DateTime CompletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationCompleted> EvaluationCompleted { get; set; }
        public virtual Student Student { get; set; }
    }
}
